### ISSUE TITLE
Stray scaleway-ubuntu-stable-bionic.list in sources.list.d (stretch image)

### ISSUE THREAD

**Issue by kevinvalk** [scaleway/image-debian#103]
The file https://github.com/scaleway/image-debian/blob/master/stretch/overlay/etc/apt/sources.list.d/scaleway-ubuntu-stable-bionic.list should not be there. **This file is only present in the stretch image.**

According https://community.online.net/t/solved-debian-is-not-debian/6602/3 this should be fixed already, but the file is still in this repository hence I am re-raising this issue.

**Comment by karibou** [comment]
Hello,
The reason for this file being there is that it points to Scaleway's PPA which contains the latest cloud-init packages with a commit to the Scaleway datasource not yet into the package (see https://code.launchpad.net/~louis/cloud-init/+git/cloud-init/+merge/349420 for details).

The cloud-init package in the official debian archive is outdated and does not contain the ScalewayDataSource required to enable cloud-init on stretch. Hence we provide a newer package using Launchpad's PPA facility.

The long term solution for Scaleway will be to host our own archive where Debian and Ubuntu package will be separate but it is not available yet.

As for the previous issue, it was caused by a faullty /etc/cloud/cloud.cfg file being used on  a previous debian image and it was solved by rebuilding the image with the correct configuration file.

I hope   that this answers your question.

kind regards,

Louis
